from typing import Final, Literal, Self

ABI_VERSION: Final[int]

class Ring:
    def __init__(self, entries: int = 256) -> None: ...
    @property
    def sq_entries(self) -> int: ...
    @property
    def cq_entries(self) -> int: ...
    @property
    def features(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: object | None,
    ) -> Literal[False]: ...
