from typing import Final, Literal, Self

ABI_VERSION: Final[int]

class Request:
    @property
    def state(
        self,
    ) -> Literal["prepared", "submitted", "completed", "cancelled"]: ...
    @property
    def done(self) -> bool: ...
    @property
    def cancelled(self) -> bool: ...
    @property
    def result(self) -> int | None: ...
    @property
    def flags(self) -> int: ...

class Ring:
    def __init__(self, entries: int = 256) -> None: ...
    @property
    def sq_entries(self) -> int: ...
    @property
    def cq_entries(self) -> int: ...
    @property
    def features(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    @property
    def pending(self) -> int: ...
    def prepare_nop(self) -> Request: ...
    def submit(self) -> int: ...
    def reap(self, max_completions: int = 64) -> list[Request]: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: object | None,
    ) -> Literal[False]: ...
