name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare:
    - name: python version
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.2"
        enable-cache: true

    - name: Install dependencies
      run: |
        uv sync --only-group dev

    - name: Lint
      run: uv run ruff check uringloop tests

    - name: Run tests
      run: pytest tests/ -v
