name: Upload Package (testing)

on:
  release:
    types: [published]
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          submodules: recursive  # Initializes and fetches submodules
          fetch-depth: 0         # Needed for submodule hashes

      - name: Install the liburing
        run: |
          cd libs
          ./configure
          make

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.2"
          enable-cache: true

      - name: Build release distributions
        run: uv build -v --no-binary

      - name: Upload distributions
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}  #
        run:  |
          python3 -m twine upload --repository testpypi dist/*
