name: Upload Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Prepare environment
        uses: ./.github/actions/prepare

      - name: Build release distributions
        run: |
          uv build -v --sdist

      - name: Upload distributions
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  #
        run:  |
          uv run twine upload --verbose --repository pypi dist/*
